[[bin]]
name = 'vo-test'
path = 'src/main.rs'

[package]
name = 'vo-test'
version = '0.1.0'
authors = ['xie.jf <xie.jf@cidi.ai>']
edition = '2018'

[lib]
name = 'vo'
path = 'src/lib.rs'

[dependencies.nalgebra]
version = '^0.21'
default-features = false

[dependencies.async-std]
version = '^1.5'
features = ['attributes']

[dependencies.opencv]
version = '0.36'
default-features = false
features = [
    'opencv-32',
    'contrib',
]
